
title: Zhuoxin Li's Website
page-top-title: Zhuoxin Li
top-section-bg-text:
home-subtitle: Zhuoxin Li&ensp;|&ensp;Vincent
copyright-text: '&copy; Zhuoxin Li 2024. All Rights Reserved.'
timezone: "America/Toronto"
